# Generated by Django 5.1.4 on 2024-12-10 11:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Merchant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('account_name', models.CharField(max_length=255)),
                ('channels', models.JSONField(default=dict)),
                ('tickets_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('merchnat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merchants', to='Merchant.client')),
            ],
        ),
    ]
