# Generated by Django 5.1.4 on 2024-12-12 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MerchantSite', '0003_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.CharField(editable=False, primary_key=True, serialize=False),
        ),
    ]
