# Generated by Django 5.1.4 on 2024-12-12 05:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Merchant', '0001_initial'),
        ('MerchantSite', '0004_alter_customer_customer_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeBase',
            fields=[
                ('kb_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('version', models.IntegerField(default=1)),
                ('file_path', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_bases', to='MerchantSite.customer')),
                ('merchant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_bases', to='Merchant.client')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.TextField()),
                ('priority', models.CharField(choices=[('1', 'Low'), ('2', 'High')], max_length=1)),
                ('channel', models.CharField(choices=[('Twitter', 'Twitter'), ('Instagram', 'Instagram'), ('Email', 'Email'), ('WhatsApp', 'WhatsApp')], max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('deferred', 'Deferred'), ('closed', 'Closed')], max_length=10)),
                ('response_recap', models.TextField(blank=True, null=True)),
                ('deferred_at', models.DateTimeField(blank=True, null=True)),
                ('closed_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='MerchantSite.customer')),
                ('merchant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='Merchant.client')),
            ],
        ),
    ]
