# Generated by Django 5.1.4 on 2024-12-12 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MerchantSite', '0006_rename_merchnat_id_customer_merchant_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_tickets', to='MerchantSite.customer'),
        ),
    ]
